import React from "react";
import { Button, Card, ErrorBlock, List, ProgressBar, Selector, Space, Steps, Switch, Tag } from "antd-mobile";
import { CheckOutline, LinkOutline, ScanCodeOutline } from "antd-mobile-icons";
import type { ExperienceBlockRendererProps } from "../block-registry";
type Row=NonNullable<ExperienceBlockRendererProps["entityRows"]>[string][number];
const f=(p:ExperienceBlockRendererProps,k:string)=>String(p.block.binding?.[k]??"").trim(),v=(r:Row,k:string,d="")=>String(r.values?.[k]??d),n=(r:Row,k:string,d=0)=>Number(r.values?.[k]??d),yes=(r:Row,k:string)=>/true|yes|enabled|available|1/i.test(v(r,k));
const bound=(p:ExperienceBlockRendererProps)=>{const entityRef=f(p,"entityRef"),rows=entityRef?p.entityRows?.[entityRef]:undefined;return entityRef&&rows?.length?{entityRef,rows}:undefined},targets=(p:ExperienceBlockRendererProps)=>Array.isArray(p.block.binding?.targets)?p.block.binding.targets.map(String):[];
const shell=(p:ExperienceBlockRendererProps,id:string,title:string,c:React.ReactNode)=><Card data-testid={`phone-${id}`} title={String(p.block.props?.title??title)}>{c}</Card>,empty=(p:ExperienceBlockRendererProps,id:string,title:string)=>shell(p,id,title,<ErrorBlock status="empty" title="尚未绑定所需数据"/>),notice=(ok:boolean,t:string)=><div style={{padding:10,background:ok?"#e7f8f2":"#fff1f0",color:ok?"#067647":"#cf1322"}}>{t}</div>;

function Critical(p:ExperienceBlockRendererProps){const b=bound(p),name=f(p,"taskNameFieldRef"),start=f(p,"startOffsetFieldRef"),duration=f(p,"durationFieldRef"),deps=f(p,"dependencyIdsFieldRef"),critical=f(p,"criticalFieldRef");if(!b||!name||!start||!duration||!deps||!critical)return empty(p,"critical-path-dependency-scheduler","关键路径依赖排期器");const ids=new Set(b.rows.map(r=>r.id)),ok=b.rows.every(r=>n(r,duration)>0&&v(r,deps).split(",").filter(Boolean).every(d=>ids.has(d)&&d!==r.id));return shell(p,"critical-path-dependency-scheduler","关键路径依赖排期器",<Space block direction="vertical"><Steps direction="vertical" current={b.rows.length-1}>{b.rows.sort((a,z)=>n(a,start)-n(z,start)).map(r=><Steps.Step key={r.id} title={v(r,name)} description={`D${n(r,start)}–${n(r,start)+n(r,duration)} · ${v(r,deps)||"起点"}`} status={yes(r,critical)?"error":"finish"}/>)}</Steps>{notice(ok,ok?"依赖链可达":"存在自依赖或孤立依赖")}<Button block color="primary" disabled={!ok} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,operation:"saveCriticalPathSchedule",targets:targets(p)})}>保存依赖排期</Button></Space>)}
function Mitre(p:ExperienceBlockRendererProps){const b=bound(p),tactic=f(p,"tacticFieldRef"),tech=f(p,"techniqueFieldRef"),coverage=f(p,"coverageFieldRef"),alerts=f(p,"alertCountFieldRef"),mitigation=f(p,"mitigationFieldRef"),tactics=b?[...new Set(b.rows.map(r=>v(r,tactic)))]:[],[activeT,setActiveT]=React.useState("");if(!b||!tactic||!tech||!coverage||!alerts||!mitigation)return empty(p,"mitre-technique-coverage-navigator","MITRE 技术覆盖导航器");const current=activeT||tactics[0],rows=b.rows.filter(r=>v(r,tactic)===current),ok=b.rows.every(r=>n(r,coverage)>=0&&n(r,coverage)<=100);return shell(p,"mitre-technique-coverage-navigator","MITRE 技术覆盖导航器",<Space block direction="vertical"><Selector columns={2} value={[current]} onChange={x=>setActiveT(String(x[0]))} options={tactics.map(x=>({label:x,value:x}))}/><List>{rows.map(r=><List.Item key={r.id} description={v(r,mitigation)} extra={<Tag color={n(r,coverage)<50?"danger":"success"}>{n(r,alerts)} 告警</Tag>}>{v(r,tech)}<ProgressBar percent={n(r,coverage)}/></List.Item>)}</List>{notice(ok,"覆盖率边界有效")}<Button block onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,operation:"openMitreMitigation",targets:targets(p)})}><ScanCodeOutline/> 查看缓解计划</Button></Space>)}
function Booking(p:ExperienceBlockRendererProps){const b=bound(p),date=f(p,"diagnosticDateFieldRef"),calendar=f(p,"calendarNameFieldRef"),schedule=f(p,"scheduleNameFieldRef"),available=f(p,"availableFieldRef"),reason=f(p,"blockedReasonFieldRef"),[day,setDay]=React.useState(b?.rows[0]?v(b.rows[0],date):"");if(!b||!date||!calendar||!schedule||!available||!reason)return empty(p,"booking-availability-troubleshooter","预约可用性故障诊断器");const dates=[...new Set(b.rows.map(r=>v(r,date)))],rows=b.rows.filter(r=>v(r,date)===day),ok=b.rows.every(r=>yes(r,available)||v(r,reason));return shell(p,"booking-availability-troubleshooter","预约可用性故障诊断器",<Space block direction="vertical"><Selector value={[day]} onChange={x=>setDay(String(x[0]))} options={dates.map(x=>({label:x,value:x}))}/><List header={rows[0]?v(rows[0],schedule):""}>{rows.map(r=><List.Item key={r.id} prefix={<Switch defaultChecked/>} description={yes(r,available)?"可预约":v(r,reason)} extra={<Tag color={yes(r,available)?"success":"danger"}>{yes(r,available)?"通过":"阻塞"}</Tag>}>{v(r,calendar)}</List.Item>)}</List>{notice(ok,"每个阻塞项都有明确原因")}<Button block onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,date:day,operation:"rerunAvailabilityDiagnostic",targets:targets(p)})}>重新诊断</Button></Space>)}
function Ports(p:ExperienceBlockRendererProps){const b=bound(p),port=f(p,"portNameFieldRef"),device=f(p,"deviceNameFieldRef"),side=f(p,"panelSideFieldRef"),occupied=f(p,"occupiedFieldRef"),vlan=f(p,"vlanFieldRef"),opposite=f(p,"oppositePortFieldRef"),[selected,setSelected]=React.useState<string[]>([]);if(!b||!port||!device||!side||!occupied||!vlan||!opposite)return empty(p,"network-port-patch-panel-composer","网络端口配线编排器");const chosen=b.rows.filter(r=>selected.includes(r.id)),ok=chosen.length===2&&chosen[0].id!==chosen[1].id&&!chosen.some(r=>yes(r,occupied))&&v(chosen[0],vlan)===v(chosen[1],vlan);return shell(p,"network-port-patch-panel-composer","网络端口配线编排器",<Space block direction="vertical"><List>{b.rows.map(r=><List.Item key={r.id} onClick={()=>setSelected(x=>x.includes(r.id)?x.filter(id=>id!==r.id):x.length<2?[...x,r.id]:[x[1],r.id])} prefix={<span style={{width:14,height:14,borderRadius:3,background:selected.includes(r.id)?"#1677ff":yes(r,occupied)?"#ff4d4f":"#52c41a"}}/>} description={`${v(r,device)} · ${v(r,side)}${v(r,opposite)?` → ${v(r,opposite)}`:""}`} extra={<Tag>{v(r,vlan)}</Tag>}>{v(r,port)}</List.Item>)}</List>{notice(ok,ok?"两端空闲且 VLAN 一致":"请选择两个兼容空闲端口")}<Button block color="primary" disabled={!ok} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,sourcePortId:selected[0],destinationPortId:selected[1],operation:"connectNetworkPorts",targets:targets(p)})}><LinkOutline/> 建立配线连接</Button></Space>)}
export function renderIndependentStructureBatch13PhoneBlock(p:ExperienceBlockRendererProps):React.ReactNode|undefined{switch(p.block.type){case"CriticalPathDependencyScheduler":return <Critical {...p}/>;case"MitreTechniqueCoverageNavigator":return <Mitre {...p}/>;case"BookingAvailabilityTroubleshooter":return <Booking {...p}/>;case"NetworkPortPatchPanelComposer":return <Ports {...p}/>;default:return undefined}}
