import React from "react";
import { Alert, Badge, Button, Card, Checkbox, Collapse, Flex, Progress, Radio, Segmented, Select, Space, Tag, Timeline, Typography } from "antd";
import { AimOutlined, CalendarOutlined, CheckCircleOutlined, DeploymentUnitOutlined, LinkOutlined, SafetyCertificateOutlined } from "@ant-design/icons";
import type { ExperienceBlockRenderer, ExperienceBlockRendererProps } from "./block-registry";
type Row=NonNullable<ExperienceBlockRendererProps["entityRows"]>[string][number];
const f=(p:ExperienceBlockRendererProps,k:string)=>String(p.block.binding?.[k]??"").trim(),v=(r:Row,k:string,d="")=>String(r.values?.[k]??d),n=(r:Row,k:string,d=0)=>Number(r.values?.[k]??d),yes=(r:Row,k:string)=>/true|yes|enabled|available|1/i.test(v(r,k));
const bound=(p:ExperienceBlockRendererProps)=>{const entityRef=f(p,"entityRef"),rows=entityRef?p.entityRows?.[entityRef]:undefined;return entityRef&&rows?.length?{entityRef,rows}:undefined},targets=(p:ExperienceBlockRendererProps)=>Array.isArray(p.block.binding?.targets)?p.block.binding.targets.map(String):[];
const shell=(p:ExperienceBlockRendererProps,id:string,title:string,c:React.ReactNode)=>p.block.props?.surface==="plain"?<section data-testid={id}>{c}</section>:<Card size="small" title={String(p.block.props?.title??title)} data-testid={id}>{c}</Card>,missing=(p:ExperienceBlockRendererProps,id:string,title:string)=>shell(p,id,title,<Alert showIcon type="info" message="区块尚未绑定所需数据"/>);

export const criticalPathScheduleValid=(tasks:Array<{id:string;start:number;duration:number;dependencies:string[]}>)=>{const ids=new Set(tasks.map(x=>x.id));return tasks.every(x=>x.start>=0&&x.duration>0&&x.dependencies.every(d=>ids.has(d)&&d!==x.id)&&x.dependencies.every(d=>{const p=tasks.find(t=>t.id===d)!;return x.start>=p.start+p.duration}))};
export const mitreCoverageValid=(rows:Array<{tactic:string;technique:string;coverage:number}>)=>rows.length>0&&new Set(rows.map(x=>`${x.tactic}|${x.technique}`)).size===rows.length&&rows.every(x=>x.tactic&&x.technique&&x.coverage>=0&&x.coverage<=100);
export const bookingDiagnosticValid=(rows:Array<{date:string;calendar:string;reason:string;available:boolean}>)=>rows.length>0&&rows.every(x=>x.date&&x.calendar&&(x.available||x.reason.trim().length>0));
export const networkPatchValid=(source:string,destination:string,rows:Array<{id:string;occupied:boolean;vlan:string}>)=>{const a=rows.find(x=>x.id===source),b=rows.find(x=>x.id===destination);return Boolean(a&&b&&source!==destination&&!a.occupied&&!b.occupied&&a.vlan===b.vlan)};

export const CriticalPathDependencySchedulerRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),name=f(p,"taskNameFieldRef"),start=f(p,"startOffsetFieldRef"),duration=f(p,"durationFieldRef"),deps=f(p,"dependencyIdsFieldRef"),critical=f(p,"criticalFieldRef");if(!b||!name||!start||!duration||!deps||!critical)return missing(p,"critical-path-dependency-scheduler","关键路径依赖排期器");const tasks=b.rows.map(r=>({id:r.id,start:n(r,start),duration:n(r,duration),dependencies:v(r,deps).split(",").filter(Boolean)})),valid=criticalPathScheduleValid(tasks),end=Math.max(...tasks.map(x=>x.start+x.duration),1);return shell(p,"critical-path-dependency-scheduler","关键路径依赖排期器",<Flex vertical gap={12}><div style={{position:"relative",padding:"8px 0"}}>{b.rows.map(r=><Flex key={r.id} align="center" gap={10} style={{marginBottom:8}}><Typography.Text style={{width:110}} ellipsis>{v(r,name)}</Typography.Text><div style={{position:"relative",height:26,flex:1,background:"var(--ant-color-fill-quaternary)"}}><div style={{position:"absolute",left:`${n(r,start)/end*100}%`,width:`${n(r,duration)/end*100}%`,height:"100%",background:yes(r,critical)?"#ff4d4f":"#1677ff",borderRadius:4}}/><span style={{position:"absolute",left:6,lineHeight:"26px",color:"white"}}>D{n(r,start)}–{n(r,start)+n(r,duration)}</span></div><Tag color={yes(r,critical)?"red":"blue"}>{v(r,deps)||"起点"}</Tag></Flex>)}</div><Alert showIcon type={valid?"success":"error"} message={valid?"依赖均存在且后继任务没有早于前置完成":"存在自依赖、孤立依赖或排期穿透"}/><Button type="primary" icon={<DeploymentUnitOutlined/>} disabled={!valid} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,operation:"saveCriticalPathSchedule",targets:targets(p)})}>保存依赖排期</Button></Flex>)};

export const MitreTechniqueCoverageNavigatorRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),tactic=f(p,"tacticFieldRef"),technique=f(p,"techniqueFieldRef"),coverage=f(p,"coverageFieldRef"),alerts=f(p,"alertCountFieldRef"),mitigation=f(p,"mitigationFieldRef"),[active,setActive]=React.useState("");if(!b||!tactic||!technique||!coverage||!alerts||!mitigation)return missing(p,"mitre-technique-coverage-navigator","MITRE 技术覆盖导航器");const tactics=[...new Set(b.rows.map(r=>v(r,tactic)))],valid=mitreCoverageValid(b.rows.map(r=>({tactic:v(r,tactic),technique:v(r,technique),coverage:n(r,coverage)}))),selected=b.rows.find(r=>r.id===active)??b.rows[0];return shell(p,"mitre-technique-coverage-navigator","MITRE 技术覆盖导航器",<Flex vertical gap={12}><div style={{display:"grid",gridTemplateColumns:`repeat(${Math.min(tactics.length,4)},minmax(0,1fr))`,gap:8}}>{tactics.map(t=><Card key={t} size="small" title={t}>{b.rows.filter(r=>v(r,tactic)===t).map(r=><Card key={r.id} size="small" hoverable onClick={()=>setActive(r.id)} style={{marginBottom:6,borderColor:selected.id===r.id?"#1677ff":undefined}}><Flex justify="space-between"><span>{v(r,technique)}</span><Badge count={n(r,alerts)} showZero/></Flex><Progress percent={n(r,coverage)} size="small" status={n(r,coverage)<50?"exception":"normal"}/></Card>)}</Card>)}</div><Collapse items={[{key:"detail",label:`缓解措施 · ${v(selected,technique)}`,children:<Typography.Paragraph>{v(selected,mitigation)}</Typography.Paragraph>}]} /><Alert showIcon type={valid?"success":"error"} message={valid?"战术/技术组合唯一，覆盖率边界有效":"存在重复技术或非法覆盖率"}/><Button icon={<SafetyCertificateOutlined/>} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,techniqueId:selected.id,operation:"openMitreMitigation",targets:targets(p)})}>查看缓解计划</Button></Flex>)};

export const BookingAvailabilityTroubleshooterRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),date=f(p,"diagnosticDateFieldRef"),calendar=f(p,"calendarNameFieldRef"),schedule=f(p,"scheduleNameFieldRef"),available=f(p,"availableFieldRef"),reason=f(p,"blockedReasonFieldRef"),[selected,setSelected]=React.useState(b?.rows[0]?.id??""),[enabled,setEnabled]=React.useState<Record<string,boolean>>({});if(!b||!date||!calendar||!schedule||!available||!reason)return missing(p,"booking-availability-troubleshooter","预约可用性故障诊断器");const valid=bookingDiagnosticValid(b.rows.map(r=>({date:v(r,date),calendar:v(r,calendar),reason:v(r,reason),available:yes(r,available)}))),row=b.rows.find(r=>r.id===selected)??b.rows[0];return shell(p,"booking-availability-troubleshooter","预约可用性故障诊断器",<Flex vertical gap={12}><Flex gap={8} wrap>{b.rows.map(r=><Button key={r.id} type={r.id===selected?"primary":"default"} danger={!yes(r,available)} onClick={()=>setSelected(r.id)}>{v(r,date)}</Button>)}</Flex><Card size="small" title={<Space><CalendarOutlined/>{v(row,schedule)}</Space>}><Flex justify="space-between" align="center"><Checkbox checked={enabled[row.id]??true} onChange={e=>setEnabled(s=>({...s,[row.id]:e.target.checked}))}>{v(row,calendar)}</Checkbox><Tag color={yes(row,available)?"green":"red"}>{yes(row,available)?"可预约":"被占用"}</Tag></Flex>{!yes(row,available)&&<Alert style={{marginTop:10}} type="warning" message={v(row,reason)}/>}</Card><Timeline items={b.rows.filter(r=>v(r,date)===v(row,date)).map(r=>({color:yes(r,available)?"green":"red",children:`${v(r,calendar)} · ${yes(r,available)?"通过":v(r,reason)}`}))}/><Alert showIcon type={valid?"info":"error"} message={valid?"逐日诊断保留了每个日历与排期的阻塞原因":"不可用日期必须给出明确原因"}/><Button icon={<AimOutlined/>} disabled={!valid} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,date:v(row,date),operation:"rerunAvailabilityDiagnostic",targets:targets(p)})}>重新诊断这一天</Button></Flex>)};

export const NetworkPortPatchPanelComposerRenderer:ExperienceBlockRenderer=p=>{const b=bound(p),port=f(p,"portNameFieldRef"),device=f(p,"deviceNameFieldRef"),side=f(p,"panelSideFieldRef"),occupied=f(p,"occupiedFieldRef"),vlan=f(p,"vlanFieldRef"),opposite=f(p,"oppositePortFieldRef"),[source,setSource]=React.useState(""),[destination,setDestination]=React.useState("");if(!b||!port||!device||!side||!occupied||!vlan||!opposite)return missing(p,"network-port-patch-panel-composer","网络端口配线编排器");const rows=b.rows.map(r=>({id:r.id,occupied:yes(r,occupied),vlan:v(r,vlan)})),valid=networkPatchValid(source,destination,rows),sides=[...new Set(b.rows.map(r=>v(r,side)))];return shell(p,"network-port-patch-panel-composer","网络端口配线编排器",<Flex vertical gap={12}><div style={{display:"grid",gridTemplateColumns:`repeat(${Math.min(sides.length,2)},minmax(0,1fr))`,gap:12}}>{sides.map(x=><Card key={x} size="small" title={x}>{b.rows.filter(r=>v(r,side)===x).map(r=><Card key={r.id} size="small" hoverable onClick={()=>source?setDestination(r.id):setSource(r.id)} style={{marginBottom:8,borderColor:[source,destination].includes(r.id)?"#1677ff":undefined,opacity:yes(r,occupied)?.6:1}}><Flex justify="space-between"><Space><Badge status={yes(r,occupied)?"error":"success"}/><strong>{v(r,port)}</strong></Space><Tag>{v(r,vlan)}</Tag></Flex><Typography.Text type="secondary">{v(r,device)}{v(r,opposite)?` → ${v(r,opposite)}`:""}</Typography.Text></Card>)}</Card>)}</div><Alert showIcon type={valid?"success":"warning"} message={valid?"两端空闲且 VLAN 一致，可以建立唯一物理连接":"请选择两个不同的空闲端口，并确保 VLAN 一致"}/><Flex gap={8}><Button onClick={()=>{setSource("");setDestination("")}}>清除选择</Button><Button type="primary" icon={<LinkOutlined/>} disabled={!valid} onClick={()=>p.onAction?.("submitRequest",{entityRef:b.entityRef,sourcePortId:source,destinationPortId:destination,operation:"connectNetworkPorts",targets:targets(p)})}>建立配线连接</Button></Flex></Flex>)};

export const INDEPENDENT_STRUCTURE_BATCH13_LABELS:Record<string,string>={CriticalPathDependencyScheduler:"关键路径依赖排期器",MitreTechniqueCoverageNavigator:"MITRE 技术覆盖导航器",BookingAvailabilityTroubleshooter:"预约可用性故障诊断器",NetworkPortPatchPanelComposer:"网络端口配线编排器"};
